/**
 * @flow
 */

export const jaMiscCodeDict = {
  'abbr': "abbreviation",
  'arch': "archaism",
  'ateji': "kanji used as phonetic symbol(s)",
  'chn': "children's language",
  'col': "colloquialism",
  'fam': "familiar language",
  'fem': "female term or language",
  'gikun': "gikun (meaning) reading",
  'hon': "honorific or respectful (sonkeigo) language",
  'hum': "humble (kenjougo) language",
  'iK': "word containing irregular kanji usage",
  'ik': "word containing irregular kana usage",
  'io': "irregular okurigana usage",
  'joc': "jocular or humorous term",
  'm-sl': "manga slang",
  'male': "male term or language",
  'obs': "obsolete term",
  'obsc': "obscure term",
  'oK': "word containing out-dated kanji",
  'ok': "out-dated or obsolete kana usage",
  'on-mim': "onomatopoeic or mimetic word",
  'P': "\"Priority\" entry, i.e. among approx. 20,000 words deemed to be common in Japanese",
  'pol': "polite (teineigo) language",
  'sens': "term with some sensitivity about its usage",
  'sl': "slang",
  'uK': "word usually written using kanji alone",
  'uk': "word usually written using kana alone",
  'vulg': "vulgar expression or word",
  'X': "rude or X-rated term (not displayed in educational software)",
};

export const jaPosCodeDict = {
  'adj-f': "noun, verb, etc. acting prenominally (incl. rentaikei)",
  'adj-i': "adjective (keiyoushi)",
  'adj-kari': "`kari' adjective (archaic)",
  'adj-ku': "`ku' adjective (archaic)",
  'adj-na': "adjectival nouns or quasi-adjectives (keiyoudoushi)",
  'adj-nari': "archaic/formal form of na-adjective",
  'adj-no': "nouns which may take the genitive case particle 'no'",
  'adj-pn': "pre-noun adjectival (rentaishi)",
  'adj-shiku': "`shiku' adjective (archaic)",
  'adj-t': "`taru' adjective",
  'adv': "adverb (fukushi)",
  'adv-to': "adverb (with particle 'to')",
  'aux': "auxiliary",
  'aux-v': "auxiliary verb",
  'conj': "conjunction",
  'ctr': "counter",
  'exp': "Expressions (phrases, clauses, etc.)",
  'id': "idiomatic expression",
  'int': "interjection (kandoushi)",
  'n': "noun (common) (futsuumeishi)",
  'n-adv': "adverbial noun (fukushitekimeishi)",
  'n-p': "proper noun",
  'n-t': "noun (temporal) (jisoumeishi)",
  'pn': "pronoun",
  'pref': "prefix",
  'prt': "particle",
  'suf': "suffix",
  'v-unspec': "verb - uspecified (usu. archaic)",
  'v1': "Ichidan verb",
  'v2a-s': "Nidan verb with u ending (archaic)",
  'v2b-k': "Nidan verb (upper class) with bu ending (archaic)",
  'v2b-s': "Nidan verb (lower class) with bu ending (archaic)",
  'v2d-k': "Nidan verb (upper class) with dzu ending (archaic)",
  'v2d-s': "Nidan verb (lower class) with dzu ending (archaic)",
  'v2g-k': "Nidan verb (upper class) with gu ending (archaic)",
  'v2g-s': "Nidan verb (lower class) with gu ending (archaic)",
  'v2h-k': "Nidan verb (upper class) with hu/fu ending (archaic)",
  'v2h-s': "Nidan verb (lower class) with hu/fu ending (archaic)",
  'v2k-k': "Nidan verb (upper class) with ku ending (archaic)",
  'v2k-s': "Nidan verb (lower class) with ku ending (archaic)",
  'v2m-k': "Nidan verb (upper class) with mu ending (archaic)",
  'v2m-s': "Nidan verb (lower class) with mu ending (archaic)",
  'v2n-s': "Nidan verb (lower class) with nu ending (archaic)",
  'v2r-k': "Nidan verb (upper class) with ru ending (archaic)",
  'v2r-s': "Nidan verb (lower class) with ru ending (archaic)",
  'v2s-s': "Nidan verb (lower class) with su ending (archaic)",
  'v2t-k': "Nidan verb (upper class) with tsu ending (archaic)",
  'v2t-s': "Nidan verb (lower class) with tsu ending (archaic)",
  'v2w-s': "Nidan verb (lower class) with u ending and we conjugation (archaic)",
  'v2y-k': "Nidan verb (upper class) with yu ending (archaic)",
  'v2y-s': "Nidan verb (lower class) with yu ending (archaic)",
  'v2z-s': "Nidan verb (lower class) with zu ending (archaic)",
  'v4b': "Yodan verb with bu ending (archaic)",
  'v4g': "Yodan verb with gu ending (archaic)",
  'v4h': "Yodan verb with hu/fu ending (archaic)",
  'v4k': "Yodan verb with ku ending (archaic)",
  'v4m': "Yodan verb with mu ending (archaic)",
  'v4n': "Yodan verb with nu ending (archaic)",
  'v4r': "Yodan verb with ru ending (archaic)",
  'v4s': "Yodan verb with su ending (archaic)",
  'v4t': "Yodan verb with tsu ending (archaic)",
  'v5aru': "Godan verb - aru special class",
  'v5b': "Godan verb with bu ending",
  'v5g': "Godan verb with gu ending",
  'v5k': "Godan verb with ku ending",
  'v5k-s': "Godan verb - Iku/Yuku special class",
  'v5m': "Godan verb with mu ending",
  'v5n': "Godan verb with nu ending",
  'v5r': "Godan verb with ru ending",
  'v5r-i': "Godan verb with ru ending (irregular verb)",
  'v5s': "Godan verb with su ending",
  'v5t': "Godan verb with tsu ending",
  'v5u': "Godan verb with u ending",
  'v5u-s': "Godan verb with u ending (special class)",
  'v5uru': "Godan verb - Uru old class verb (old form of Eru)",
  'v5z': "Godan verb with zu ending",
  'vi': "intransitive verb",
  'vk': "Kuru verb - special class",
  'vs': "noun or participle which takes the aux. verb suru",
  'vs-c': "su verb - precursor to the modern suru",
  'vs-i': "expression using the aux. verb suru",
  'vs-s': "suru verb - special class",
  'vt': "transitive verb",
  'vz': "Ichidan verb - -zuru special class (alternative form of -jiru verbs)"
};
